{"name": "test_expected_to_fail_example", "status": "skipped", "statusDetails": {"message": "XFAIL This test is expected to fail due to a known bug (ID-123).\n\nAssertionError: This is an expected failure.\nassert 1 == 2", "trace": "self = <TestCases.test_010_Advanced_Features.TestAdvancedFeatures object at 0x00000200D88376F0>\n\n    @pytest.mark.xfail(reason=\"This test is expected to fail due to a known bug (ID-123).\")\n    def test_expected_to_fail_example(self):\n        \"\"\"\n        This test is marked as an expected failure (xfail).\n        \"\"\"\n        print(\"\\nExecuting a test that is expected to fail.\")\n        # This simulates a feature that is currently broken\n>       assert 1 == 2, \"This is an expected failure.\"\nE       AssertionError: This is an expected failure.\nE       assert 1 == 2\n\nTestCases\\test_010_Advanced_Features.py:66: AssertionError"}, "description": "\nThis test is marked as an expected failure (xfail).\n", "attachments": [{"name": "stdout", "source": "accc22b1-8a57-4392-96ff-45a67a19c6de-attachment.txt", "type": "text/plain"}], "start": 1761197698194, "stop": 1761197698195, "uuid": "680af165-272a-4eb3-bee8-e42d5f6b6d99", "historyId": "b67123b0112503c33b5c0caf8d0757a4", "testCaseId": "b67123b0112503c33b5c0caf8d0757a4", "fullName": "TestCases.test_010_Advanced_Features.TestAdvancedFeatures#test_expected_to_fail_example", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_010_Advanced_Features"}, {"name": "subSuite", "value": "TestAdvancedFeatures"}, {"name": "host", "value": "ASCENDI-NFVVIL5"}, {"name": "thread", "value": "15604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_010_Advanced_Features"}], "titlePath": ["TestCases", "test_010_Advanced_Features.py", "TestAdvancedFeatures"]}